name: Deploy Bot

on:
  push:
    branches: ["main"]
    paths:
      - "src/apps/bot/**"
      - ".github/workflows/deploy-bot.yml"


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------------- Upload only bot directory ----------------
      - name: Upload bot files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "*"
          target: "/var/www/kiri-bot"
          strip_components: 3

      # ---------------- SSH commands on server ----------------
      - name: Install deps & restart PM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/kiri-bot
            echo "TG_TOKEN=${{ secrets.TG_TOKEN }}" > .env
            echo "TG_OWNER_CHAT_ID=${{ secrets.TG_OWNER_CHAT_ID }}" >> .env
            echo "TG_ADMIN_CHAT_ID=${{ secrets.TG_ADMIN_CHAT_ID }}" >> .env
            echo "TG_DEV_CHAT_ID=${{ secrets.TG_DEV_CHAT_ID }}" >> .env
            echo "TG_DEBUG_CHAT_ID=${{ secrets.TG_DEBUG_CHAT_ID }}" >> .env

            npm install --production
            pm2 restart kiri-bot || pm2 start bot.js --name kiri-bot
            pm2 save
